# Generated by Django 4.1 on 2022-08-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myMenu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="price",
        ),
    ]
